### ISSUE TITLE
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved since PHP 7.2

### ISSUE THREAD

**Issue by masterix65** [SplashSync/Php-Bundle#2]
`PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in \vendor\splash\php-bundle\Annotation\Object.php on line 11`

In symfony profiler:
`Compile Error: Cannot use 'Object' as class name as it is reserved`

The error occured while using Sylius-Bundle

It should be renamed to anything else not reserved.

**Comment by BadPixxel** [comment]
Hi,

We are working hard on this Bundle to improve our whole bundles approch for Connectors. 

Sylius Bundle will be updated soon with all those changes. For next releases will be compatible for PHP 7.2, but up to now stay in 7.1 please. 

Best regards
